### ISSUE TITLE
(sec p0) Cross-site Scripting (XSS)

### ISSUE THREAD

**Issue by graphific** [20treeAI/titiler#8]
Theres a bunch of `unsanitized input from an HTTP parameter flows into the return value of wmts, where it is used to render an HTML page returned to the user. This may result in a Cross-Site Scripting attack (XSS).`

wmts: in https://github.com/20treeAI/titiler/blob/6bfc1b891d5bcdb4c0f27a1c5e84dee13e560c2f/src/titiler/core/titiler/core/factory.py#L705
and
https://github.com/20treeAI/titiler/blob/6bfc1b891d5bcdb4c0f27a1c5e84dee13e560c2f/src/titiler/mosaic/titiler/mosaic/factory.py#L497

tilejson in
https://github.com/20treeAI/titiler/blob/6bfc1b891d5bcdb4c0f27a1c5e84dee13e560c2f/src/titiler/core/titiler/core/factory.py#L618
and
https://github.com/20treeAI/titiler/blob/6bfc1b891d5bcdb4c0f27a1c5e84dee13e560c2f/src/titiler/mosaic/titiler/mosaic/factory.py#L402

This is detected by snyk, and the filtering is not always on point but commonly values can be escaped using something like `pydash.strings.escape`

https://app.snyk.io/org/roelof/project/1d38e19f-88c0-41c9-8804-c88c044ef226

**Comment by jennaramdenee** [comment]
Closing here and in snyk since this is not customer facing code
